###
GET http://localhost:3001/books
###

###
POST http://localhost:3001/books
Content-Type: application/json

{
    "title": "x",
    "author": "y",
    "isbn": 25
}

###

DELETE http://localhost:3000/books/25
